### ISSUE TITLE
Create Evaluation Web Page

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#12]
Design and create the Evaluation web page using evaluation template. Students can choose a score based on a category and click a button to save their results.

**Comment by shikharchaure** [comment]
Task Test : 
1. Go to login page  - https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/login.
Enter email id and click on submit button. You will receive a unique confirmation code on your email Id.
2.You will be redirected to a page which asks for Confirmation Code.
3. Enter confirmation code, you will be redirected to the evaluation page.
4. The evaluation page has one drop down for each evaluation metric, select an entry from each drop down for each teammate. You should see a self evaluation and a evaluation for other students, identified by the student's name. There will be 5 drop down boxes per evaluation with categories, role, leadership, participation, professionalism, and quality. There is also a submit button at the bottom. 
5. After filling all entries, click on the "Submit Evaluations" button you should see a new page which displays "Thank you for your reviews".

**Comment by shikharchaure** [comment]
Task Test ;
1. Go to login page - https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/login.
Enter email id and click on submit button. You will receive a unique confirmation code on your email Id.
2.You will be redirected to a page which asks for Confirmation Code.
3. Enter confirmation code, you will be redirected to the evaluation page.
4. The evaluation page has one drop down for each evaluation metric, select an entry from each drop down for each teammate. You should see a self evaluation and a evaluation for other students, identified by the student's name. There will be 5 drop down boxes per evaluation with categories, role, leadership, participation, professionalism, and quality. There is also a submit button at the bottom. 
5. It is mandatory to select all values before proceeding.If the "Submit Evaluations" button is pressed before selecting all values from drop down,you will see a prompt saying " Select item from drop down".

**Comment by shikharchaure** [comment]
Task Test :
1.  Go to: https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/EvaluationPage.html
2.  Since you are not signed in you will be redirected to the confirmation page.
