### ISSUE TITLE
Evaluation Score

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#15]
As a student I want my score calculated so I can get evaluation feedback

**Comment by apellechia** [comment]
Acceptance Test:

1. In the database, create a team in table, Teams or use one that's already there. Also, verify that you and at least one other student are listed in Logininfo
2. In the database, add students to your team in table, StudentTeams. To add teammates, add the team id and the student id for each student you would like to add on the team (students from Logininfo). Add you and another student listed in Logininfo to the team you created.
3. Login to the peer evaluation system
4. You will be redirected to the evaluation page (URL: https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/EvaluationPage.html)
5. You should see a self evaluation and an evaluation for another student, identified by the students name
6. Fill out every evaluation metric for each student and click submit. For simplicity and to check for correctness, makes each evaluation the same number. 
7. You will be redirected to a page that says "Your reviews have successfully submitted"
8. Go to the database and go to table Evaluationdata. Verify that the two reviews you added are there. 
9. You can rerun the test using a different number of students

**Comment by shikharchaure** [comment]
Acceptance Test:

1. In the database, create a team in table, Teams or use one that's already there. Also, verify that you and at least one other student are listed in Logininfo
2. In the database, add students to your team in table, StudentTeams. To add teammates, add the team id and the student id for each student you would like to add on the team (students from Logininfo). Add you and another student listed in Logininfo to the team you created.
3. Login to the peer evaluation system
4. You will be redirected to the evaluation page (URL: https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/EvaluationPage.html)
5. You should see a self evaluation and an evaluation for another student, identified by the students 
6. Click Submit Evaluations without filling anything out. It is mandatory to select all values before proceeding. If the "Submit Evaluations" button is pressed before selecting all values from drop down,you will see a prompt saying " Select item from drop down".
