### ISSUE TITLE
Scores are saved to the database

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#18]
Evaluation scores are saved to the database and these scores are associated with a student giving the evaluation and a team member

**Comment by lingbohu** [comment]
Task Test :

1. Make sure you are in our database as a student and also you are in a team with teammates, and you never submit a same evaluation before.
1. Go to login page - https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/login.
2. Enter email and click on submit button. You will receive the confirmation code for your email login.
3. You will be redirected to a page which asks for confirmation code, enter it, you will be redirected to the evaluation page.
4. Fill all the entries, click on the "Submit Evaluations" button, your evaluation should be stored in database.

**Comment by lingbohu** [comment]
Task Test:

1. Login to the database.
2. Open the table Evaluationdata.
3. Check if your id is saved in Evaluator, your teammate's id is saved in studentid, and your evaluation scores are saved correctly.

**Comment by lingbohu** [comment]
Task Test :

1. Go to: https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/EvaluationPage.html
2. Since you are not login in you will be redirected to the confirmation page.
