### ISSUE TITLE
Update scores in database 

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#22]
When a student updates the their evaluation scores and saves them, the scores should be updated instead of inserting another evaluation.

**Comment by lingbohu** [comment]
Task Test:

1. Make sure you submitted an evaluation before.
2. Go to login page - https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/login.
3. Enter email and click on submit button. You will receive the confirmation code for your email login.
4. You will be redirected to a page which asks for confirmation code, enter it, you will be redirected to the evaluation page.
5. Revise your evaluation by selecting the one you want to revise from drop down, click on the "Submit Evaluations" button, your evaluation should be updated and stored in database.

**Comment by lingbohu** [comment]
Task Test:

1. Login to the database.
2. Open the table Evaluationdata.
3. Check if the evaluation you revised is updated, not insert a new row. Your id is saved in Evaluator, your teammate's id is saved in studentid, both of them should stay the same. And your evaluation scores are updated correctly.

**Comment by lingbohu** [comment]
Task Test :

1. Go to: https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/EvaluationPage.html
2. Since you are not login in you will be redirected to the confirmation page.
