### ISSUE TITLE
Create Confirmation Code Page

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#27]
Create a page to enter your confirmation code. Change login to redirect to this page on success. Add key binding to pages as well

**Comment by shikharchaure** [comment]
Acceptance Test:
1. Go to the confirmation code page: https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/ConfirmationCodePage.html
2. Enter the confirmation code received on your email and click on Submit button.
3. If same code is entered then, you should see a message "Welcome to Evaluation Page".
4. If code is incorrect, you should see a message "Not a valid code".
