### ISSUE TITLE
Normalize Scores

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#32]
As an instructor, I want to have peer evaluation scores normalized so that I know how my students performed.

**Comment by shikharchaure** [comment]
Acceptance Test : 
1. Make sure you have access to cheshire server, ssh to cheshire server with your username. 
Example : ssh schaure@cheshire.cse.buffalo.edu
2.  Go to cse-442b folder under /web/CSE442-542/2019-Summer
Execute the command : 
	java -jar getScores.jar "courseName" "fileName"
Example :  	java -jar getScores.jar "cse 542" "cse542Scores"
3. After hitting enter, if there are students enrolled in the course you should see all students enrolled in this course with their normalised scores, and the same will be written into a file.

**Comment by shikharchaure** [comment]
Acceptance Test : 
1. Make sure you have access to cheshire server , ssh to cheshire server with your username. 
Example : ssh schaure@cheshire.cse.buffalo.edu
2.  Go to cse-442b folder under /web/CSE442-542/2019-Summer
Execute the command : 
	java -jar getScores.jar "courseName" "fileName"
Example :  	java -jar getScores.jar "cse 542" "cse542Scores"
3. After hitting enter, if there are no students enrolled in the course you should see a message "No students enrolled for this course"

**Comment by shikharchaure** [comment]
Acceptance Test : 
1. Make sure you have access to cheshire server , ssh to cheshire server with your username. 
Example : ssh schaure@cheshire.cse.buffalo.edu
2.  Go to cse-442b folder under /web/CSE442-542/2019-Summer
Execute the command : 
	java -jar getScores.jar "courseName" "fileName"
Example :  	java -jar getScores.jar "cse 542" "cse542Scores"
3. After hitting enter, if there is no couse of this name, you should see a message 
"No course of this name".
