### ISSUE TITLE
Create Tables For Courses

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#33]
Create tables, Courses to store active classes and StudentCourses to store the students course confirmation code

**Comment by lingbohu** [comment]
Task Test:

1. Login to the database
2. There should be two tables named Courses and StudentCourses
3. Open the Courses table, there should be 2 columns in this table: integer field 'courseid'(the primary key), varchar field 'coursename'
4. Open the StudentCourses table, there should be 4 columns in this table: integer field 'id'(the primary key), integer field 'studentid'(foreign key as it points to the primary key of the Logininfo table), the integer field 'courseid'(foreign key as it points to the primary key of the Courses table), and varchar field 'confirmationcode'
