### ISSUE TITLE
Modify Tables to Handle Multiple Classes

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#34]
Change the current tables to work with multiple classes like removing confirmation code in Login and adding a course in EvaluationData and Teams

**Comment by lingbohu** [comment]
Task Test:

1. Login to the database
2. There should be several tables have been modified: Evaluationdata, Logininfo, StudentCourses, StudentTeams, Teams
3. Open the Evaluationdata table, there should be an integer field 'courseid' added(foreign key as it points to the primary key of the Courses table)
4. Open the Logininfo table, you should notice that 'confirmationcode' and 'coursenumber' are dropped
5. Open the StudentCourses table, there should be an integer field 'courseid'(foreign key as it points to the primary key of the Courses table) and a varchar field 'confirmationcode' added
6. Open the StudentTeams table, there should be a integer field 'studentid' added(foreign key as it points to the primary key of the Logininfo table)
7. Open the Teams table, there should be a integer field 'courseid' added(foreign key as it points to the primary key of the Courses table)
