### ISSUE TITLE
Get all student from a single class

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#38]
Get all students emails id's from a single class so you know whose evaluations you need to normalize

**Comment by shikharchaure** [comment]
Task Test : 
1. Make sure you have access to cheshire server , ssh to cheshire server with your username. 
Example : ssh schaure@cheshire.cse.buffalo.edu
2.  Go to cse-442b folder under /web/CSE442-542/2019-Summer
Execute the command : 
	java -jar getScores.jar "courseName" "fileName"
Example :  	java -jar getScores.jar "cse 542" "cse542Scores"
3. After hitting enter, if there are students enrolled in the course you should see the list of students emailId. 
4. You will be able to see the above output only if there is a course in the Courses Table in the database and there is atleast one student associated with that course.

**Comment by shikharchaure** [comment]
Task Test : 
1. Make sure you have access to cheshire server , ssh to cheshire server with your username. 
Example : ssh schaure@cheshire.cse.buffalo.edu
2.  Go to cse-442b folder under /web/CSE442-542/2019-Summer
Execute the command : 
	java -jar getScores.jar "courseName" "fileName"
Example :  	java -jar getScores.jar "cse 542" "cse542Scores"
3. After hitting enter, if there are no students enrolled in the course you should see a message:
 "No students enrolled for this course".
