### ISSUE TITLE
Normalize Scores

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#40]
Normalize scores for each category per student ie get the total score possible and figure out the percentage for each evaluation metrics

**Comment by shikharchaure** [comment]
Task Test :
1. Make sure you have access to cheshire server , ssh to cheshire server with your username.
Example : ssh schaure@cheshire.cse.buffalo.edu
2. Go to cse-442b folder under /web/CSE442-542/2019-Summer
Execute the command :
java -jar getScores.jar "courseName" "fileName"
Example : java -jar getScores.jar "cse 542" "cse542Scores"
3. After hitting enter :for every student whose evaluation is done, all the values of evaluation metrics (leadership, quality, professionalism, role, participation) will be fetched, summed up(individualSum), then the sum of these individualSum(totalSum) is calculated.
Finally normalised score is calculated as individualSum/totalSum for each student.
These normalised scores are displayed for each student.

**Comment by shikharchaure** [comment]
Task Test :
1. Make sure you have access to cheshire server , ssh to cheshire server with your username.
Example : ssh schaure@cheshire.cse.buffalo.edu
2. Go to cse-442b folder under /web/CSE442-542/2019-Summer
Execute the command :
java -jar getScores.jar "courseName" "fileName"
Example : java -jar getScores.jar "cse 542" "cse542Scores"
3. After hitting enter, for every student whose evaluation is not done you should see 0.
