### ISSUE TITLE
Save students scores to a file

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#41]
Save students score to a file which has student email and their normalised score.

**Comment by shikharchaure** [comment]
Task Test :
1. Make sure you have access to cheshire server , ssh to cheshire server with your username.
Example : ssh schaure@cheshire.cse.buffalo.edu
2. Go to cse-442b folder under /web/CSE442-542/2019-Summer
Execute the command :
java -jar getScores.jar "courseName" "fileName"
Example : java -jar getScores.jar "cse 542" "cse542Scores"
3. After hitting enter, normalized score of each student and the same will be written to the file.
By default a csv file is created and if any extension is given like .txt/.xls the file is saved in that format.
