### ISSUE TITLE
Create Student Login Webpage

### ISSUE THREAD

**Issue by apellechia** [cse522summer2019/project#6]
Create a login page with a textbox to enter email.

**Comment by shikharchaure** [comment]
1. Go to login page. URL: https://www-student.cse.buffalo.edu/CSE442-542/2019-Summer/cse-442b/login
2. Enter valid email Id of format : name@buffalo.edu.
3. If invalid email is entered, you should see a pop up which says "Email address is invalid".
4. If valid email is entered, you should see a pop up saying "Confirmation code sent ".
